openapi: 3.1.0
info:
  title: Google Drive File Reader
  version: 1.0.0
servers:
  - url: https://www.googleapis.com
paths:
  /drive/v3/files/{fileId}:
    get:
      operationId: getDriveFileMetadata
      summary: Récupère les métadonnées d’un fichier Drive
      parameters:
        - name: fileId
          in: path
          required: true
          schema:
            type: string
        - name: fields
          in: query
          required: false
          schema:
            type: string
            example: name,mimeType,modifiedTime
      responses:
        '200':
          description: Métadonnées du fichier
          content:
            application/json:
              schema:
                type: object
  /drive/v3/files/{fileId}/export:
    get:
      operationId: exportDriveDocAsText
      summary: Exporte un fichier Google Docs en texte brut
      parameters:
        - name: fileId
          in: path
          required: true
          schema:
            type: string
        - name: mimeType
          in: query
          required: true
          schema:
            type: string
            example: text/plain
      responses:
        '200':
          description: Contenu du fichier exporté
          content:
            text/plain:
              schema:
                type: string
components: {}